service: service:VLLM
name: llama3.1
version: 70b-instruct-fp16-5526
bentoml_version: 1.3.14
creation_time: '2024-11-21T09:06:11.153276+00:00'
labels:
  model_name: meta-llama/Meta-Llama-3.1-70B-Instruct
  openllm_alias: 70b,70b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: llama3.1
services:
- name: llama3.1
  service: ''
  models:
  - tag: meta-llama--meta-llama-3.1-70b-instruct:945c8663693130f8be2ee66210e062158b2a9693
    module: null
    creation_time: '2024-11-21T09:06:11.151412+00:00'
    registry: huggingface
    metadata:
      model_id: meta-llama/meta-llama-3.1-70b-instruct
      revision: 945c8663693130f8be2ee66210e062158b2a9693
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: llama3.1
    resources:
      gpu: 2
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: llama3.1
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
