service: service:VLLM
name: pixtral
version: 124b-2411-9567
bentoml_version: 1.4.5
creation_time: '2025-03-17T10:26:34.677551+00:00'
labels:
  generator: openllm
  owner: bentoml-team
  aliases: 124b-2411,124b
models: []
entry_service: pixtral
services:
- name: pixtral
  service: ''
  models:
  - tag: mistralai--pixtral-large-instruct-2411:f724a069ee9f54a07410e38d60a616d7
    module: null
    creation_time: '2025-03-17T10:26:34.661751+00:00'
    registry: huggingface
    metadata:
      model_id: mistralai/pixtral-large-instruct-2411
      revision: 8f57ad2469ff52595e776d6717155492bf7f4830
      endpoint: https://huggingface.co
      include: null
      exclude:
      - '*.pth'
      - '*.pt'
  dependencies: []
  config:
    name: pixtral
    resources:
      gpu: 4
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
- name: UV_NO_PROGRESS
  value: '1'
- name: HF_HUB_DISABLE_PROGRESS_BARS
  value: '1'
- name: VLLM_LOGGING_CONFIG_PATH
  value: /tmp/tmptmyytt90/logging-config.json
schema:
  name: pixtral
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: Who are you? Please respond in pirate speak!
          title: Prompt
          type: string
        max_tokens:
          default: 4096
          maximum: 4096
          minimum: 128
          title: Max Tokens
          type: integer
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: sights
    route: /sights
    batchable: false
    input:
      properties:
        prompt:
          default: Who are you? Please respond in pirate speak!
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
        max_tokens:
          default: 4096
          maximum: 4096
          minimum: 128
          title: Max Tokens
          type: integer
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 2
image:
  base_image: python:3.11-slim
  python_version: '3.11'
  commands:
  - export UV_COMPILE_BYTECODE=1
  - apt-get update && apt-get install -q -y --no-install-recommends --allow-remove-essential
    ca-certificates gnupg2 bash build-essential git
  python_requirements: 'bentoml>=1.4.3

    vllm==0.7.3

    kantoku>=0.18.1

    fastapi

    openai>=1.61.0

    pyyaml

    Pillow

    mistral_common[opencv]

    mistral_common[opencv]

    bentoml==1.4.5

    '
  post_commands:
  - uv pip install --compile-bytecode flashinfer-python --find-links https://flashinfer.ai/whl/cu124/torch2.5
  scripts: {}
