alias:
- 24b-2501
- 24b
build:
  exclude:
  - consolidated*
engine_config:
  model: mistralai/Mistral-Small-24B-Instruct-2501
project: vllm-chat
service_config:
  envs:
  - name: HF_TOKEN
  name: mistral
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
