engine_config:
  max_model_len: 4096
  model: deepseek-ai/DeepSeek-R1-Distill-Llama-70B
  tensor_parallel_size: 2
extra_envs:
- name: HF_TOKEN
project: vllm-chat
server_config:
  enable_reasoning: true
  reasoning_parser: deepseek_r1
service_config:
  name: deepseek-r1-distill
  resources:
    gpu: 2
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
