engine_config:
  max_model_len: 4096
  model: neuralmagic/DeepSeek-R1-Distill-Qwen-14B-quantized.w8a8
project: vllm-chat
server_config:
  reasoning_parser: deepseek_r1
  tool_call_parser: llama3_json
service_config:
  name: deepseek
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
