service: service:VLLM
name: qwen2
version: 7b-instruct-fp16-7323
bentoml_version: 1.3.20
creation_time: '2025-01-22T07:15:01.936048+00:00'
labels:
  model_name: Qwen/Qwen2-7B-Instruct
  openllm_alias: 7b,7b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: qwen2
services:
- name: qwen2
  service: ''
  models:
  - tag: qwen--qwen2-7b-instruct:a7201ccb9ac5f9c181a7399dbf434599
    module: null
    creation_time: '2025-01-22T07:15:01.934276+00:00'
    registry: huggingface
    metadata:
      model_id: qwen/qwen2-7b-instruct
      revision: f2826a00ceef68f0f2b946d945ecc0477ce4450c
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: qwen2
    resources:
      gpu: 1
      gpu_type: nvidia-l4
    traffic:
      timeout: 300
envs: []
schema:
  name: qwen2
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
