alias:
- 32b
engine_config:
  max_model_len: 8192
  model: Qwen/Qwen2.5-Coder-32B-Instruct
project: vllm-chat
server_config:
  enable_auto_tool_choice: true
  enable_tool_call_parser: true
  tool_call_parser: llama3_json
service_config:
  name: qwen2.5-coder
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
