alias:
- 8b-2410
- 8b
build:
  exclude:
  - consolidated*
engine_config:
  dtype: half
  model: mistralai/Ministral-8B-Instruct-2410
project: vllm-chat
service_config:
  envs:
  - name: HF_TOKEN
  name: mistral
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
