service: service:VLLM
name: gemma
version: 2b-instruct-fp16-b322
bentoml_version: 1.3.21
creation_time: '2025-02-07T01:48:09.352086+00:00'
labels:
  openllm_alias: 2b,2b-instruct
  model_name: google/gemma-2b-it
models: []
entry_service: gemma
services:
- name: gemma
  service: ''
  models:
  - tag: google--gemma-2b-it:1a3cd0c32a1aaf9eb750751058088ef8
    module: null
    creation_time: '2025-02-07T01:48:09.231879+00:00'
    registry: huggingface
    metadata:
      model_id: google/gemma-2b-it
      revision: 96988410cbdaeb8d5093d1ebdc5a8fb563e02bad
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: gemma
    resources:
      gpu: 1
      gpu_type: nvidia-rtx-3060
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: gemma
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: sights
    route: /sights
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 2
image:
  base_image: python:3.11-slim
  python_version: '3.11'
  commands:
  - apt-get update && apt-get install -q -y --no-install-recommends --allow-remove-essential
    ca-certificates gnupg2 bash build-essential git
  python_requirements: '--index-url https://pypi.org/simple


    a2wsgi==1.10.8

    aiohappyeyeballs==2.4.4

    aiohttp==3.11.12

    aiohttp-cors==0.7.0

    aiosignal==1.3.2

    aiosqlite==0.21.0

    airportsdata==20241001

    annotated-types==0.7.0

    anyio==4.8.0

    appdirs==1.4.4

    asgiref==3.8.1

    astor==0.8.1

    async-timeout==5.0.1

    attrs==25.1.0

    bentoml==1.3.21

    blake3==1.0.4

    cachetools==5.5.1

    cattrs==23.1.2

    certifi==2025.1.31

    charset-normalizer==3.4.1

    click==8.1.8

    click-option-group==0.5.6

    cloudpickle==3.1.1

    colorful==0.5.6

    compressed-tensors==0.9.0

    deepmerge==2.0

    deprecated==1.2.18

    depyf==0.18.0

    dill==0.3.9

    diskcache==5.6.3

    distlib==0.3.9

    distro==1.9.0

    einops==0.8.0

    exceptiongroup==1.2.2

    fastapi==0.115.8

    filelock==3.17.0

    frozenlist==1.5.0

    fs==2.4.16

    fsspec==2025.2.0

    gguf==0.10.0

    google-api-core==2.24.1

    google-auth==2.38.0

    googleapis-common-protos==1.66.0

    grpcio==1.70.0

    h11==0.14.0

    httpcore==1.0.7

    httptools==0.6.4

    httpx==0.28.1

    httpx-ws==0.7.1

    huggingface-hub==0.28.1

    idna==3.10

    importlib-metadata==8.5.0

    inflection==0.5.1

    iniconfig==2.0.0

    interegular==0.3.3

    jinja2==3.1.5

    jiter==0.8.2

    jsonschema==4.23.0

    jsonschema-specifications==2024.10.1

    kantoku==0.18.1

    lark==1.2.2

    lm-format-enforcer==0.10.9

    markdown-it-py==3.0.0

    markupsafe==3.0.2

    mdurl==0.1.2

    mistral-common==1.5.2

    mpmath==1.3.0

    msgpack==1.1.0

    msgspec==0.19.0

    multidict==6.1.0

    nest-asyncio==1.6.0

    networkx==3.2.1

    numpy==1.26.4

    nvidia-cublas-cu12==12.4.5.8

    nvidia-cuda-cupti-cu12==12.4.127

    nvidia-cuda-nvrtc-cu12==12.4.127

    nvidia-cuda-runtime-cu12==12.4.127

    nvidia-cudnn-cu12==9.1.0.70

    nvidia-cufft-cu12==11.2.1.3

    nvidia-curand-cu12==10.3.5.147

    nvidia-cusolver-cu12==11.6.1.9

    nvidia-cusparse-cu12==12.3.1.170

    nvidia-ml-py==12.570.86

    nvidia-nccl-cu12==2.21.5

    nvidia-nvjitlink-cu12==12.4.127

    nvidia-nvtx-cu12==12.4.127

    openai==1.61.1

    opencensus==0.11.4

    opencensus-context==0.1.3

    opencv-python-headless==4.11.0.86

    opentelemetry-api==1.30.0

    opentelemetry-instrumentation==0.51b0

    opentelemetry-instrumentation-aiohttp-client==0.51b0

    opentelemetry-instrumentation-asgi==0.51b0

    opentelemetry-sdk==1.30.0

    opentelemetry-semantic-conventions==0.51b0

    opentelemetry-util-http==0.51b0

    outlines==0.1.11

    outlines-core==0.1.26

    packaging==24.2

    partial-json-parser==0.2.1.1.post5

    pathspec==0.12.1

    pillow==10.4.0

    pip-requirements-parser==32.0.1

    platformdirs==4.3.6

    pluggy==1.5.0

    prometheus-client==0.21.1

    prometheus-fastapi-instrumentator==7.0.2

    prompt-toolkit==3.0.50

    propcache==0.2.1

    proto-plus==1.26.0

    protobuf==5.29.3

    psutil==6.1.1

    py-cpuinfo==9.0.0

    py-spy==0.4.0

    pyasn1==0.6.1

    pyasn1-modules==0.4.1

    pybind11==2.13.6

    pycountry==24.6.1

    pydantic==2.10.6

    pydantic-core==2.27.2

    pygments==2.19.1

    pyparsing==3.2.1

    pytest==8.3.4

    python-dateutil==2.9.0.post0

    python-dotenv==1.0.1

    python-json-logger==3.2.1

    python-multipart==0.0.20

    pyyaml==6.0.2

    pyzmq==26.2.1

    questionary==2.1.0

    ray==2.42.0

    referencing==0.36.2

    regex==2024.11.6

    requests==2.32.3

    rich==13.9.4

    rpds-py==0.22.3

    rsa==4.9

    safetensors==0.5.2

    schema==0.7.7

    sentencepiece==0.2.0

    setuptools==75.8.0

    simple-di==0.1.5

    six==1.17.0

    smart-open==7.1.0

    sniffio==1.3.1

    starlette==0.45.3

    sympy==1.13.1

    tiktoken==0.7.0

    tokenizers==0.21.0

    tomli==2.2.1

    tomli-w==1.2.0

    torch==2.5.1

    torchaudio==2.5.1

    torchvision==0.20.1

    tornado==6.4.2

    tqdm==4.67.1

    transformers==4.48.2

    triton==3.1.0

    typing-extensions==4.12.2

    urllib3==2.3.0

    uv==0.5.29

    uvicorn==0.34.0

    uvloop==0.21.0

    virtualenv==20.29.1

    vllm==0.7.1

    watchfiles==1.0.4

    wcwidth==0.2.13

    websockets==14.2

    wrapt==1.17.2

    wsproto==1.2.0

    xformers==0.0.28.post3

    xgrammar==0.1.11

    yarl==1.18.3

    zipp==3.21.0

    '
  post_commands: []
  scripts: {}
