service: service:VLLM
name: qwen2vl
version: 7b-instruct-fp16-8f80
bentoml_version: 1.3.19
creation_time: '2025-01-08T02:26:19.085543+00:00'
labels:
  model_name: Qwen/Qwen2-VL-7B-Instruct
  openllm_alias: 7b
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: qwen2vl
services:
- name: qwen2vl
  service: ''
  models:
  - tag: qwen--qwen2-vl-7b-instruct:5f989a58db9accf10226bac47772ed50
    module: null
    creation_time: '2025-01-08T02:26:19.083321+00:00'
    registry: huggingface
    metadata:
      model_id: qwen/qwen2-vl-7b-instruct
      revision: a7a06a1cc11b4514ce9edcde0e3ca1d16e5ff2fc
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: qwen2vl
    resources:
      gpu: 1
      gpu_type: nvidia-l4
    traffic:
      timeout: 300
envs: []
schema:
  name: qwen2vl
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
