service: service:VLLM
name: pixtral
version: 12b-240910-8551
bentoml_version: 1.3.14
creation_time: '2024-11-21T09:09:20.410970+00:00'
labels:
  model_name: mistral-community/pixtral-12b-240910
  openllm_alias: 12b, 12b-vision
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: pixtral
services:
- name: pixtral
  service: ''
  models:
  - tag: mistral-community--pixtral-12b-240910:59794e97cb4f322f6223bb0d57b4d7523f0e27c6
    module: null
    creation_time: '2024-11-21T09:09:20.408974+00:00'
    registry: huggingface
    metadata:
      model_id: mistral-community/pixtral-12b-240910
      revision: 59794e97cb4f322f6223bb0d57b4d7523f0e27c6
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: pixtral
    resources:
      gpu: 1
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs: []
schema:
  name: pixtral
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
