service: service:VLLM
name: qwen2.5
version: 14b-instruct-fp16-8019
bentoml_version: 1.3.20
creation_time: '2025-01-22T07:14:49.612662+00:00'
labels:
  model_name: Qwen/Qwen2.5-14B-Instruct
  openllm_alias: 14b,14b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: qwen2.5
services:
- name: qwen2.5
  service: ''
  models:
  - tag: qwen--qwen2.5-14b-instruct:7f451532dd40bdace4af0878f2e6d5a9
    module: null
    creation_time: '2025-01-22T07:14:49.610862+00:00'
    registry: huggingface
    metadata:
      model_id: qwen/qwen2.5-14b-instruct
      revision: cf98f3b3bbb457ad9e2bb7baf9a0125b6b88caa8
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: qwen2.5
    resources:
      gpu: 1
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs: []
schema:
  name: qwen2.5
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
