engine_config:
  dtype: half
  max_model_len: 2048
  model: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
extra_labels:
  model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  openllm_alias: 1.5b,1.5b-math
project: vllm-chat
service_config:
  name: deepseek-r1-distill
  resources:
    gpu: 1
    gpu_type: nvidia-rtx-3060
  traffic:
    timeout: 300
