service: service:VLLM
name: mixtral
version: 8x7b-instruct-v0.1-fp16-5142
bentoml_version: 1.3.10
creation_time: '2024-10-31T01:33:37.715815+00:00'
labels:
  model_name: mistralai/Mixtral-8x7B-Instruct-v0.1
  openllm_alias: 8x7b,8x7b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: mixtral
services:
- name: mixtral
  service: ''
  models: []
  dependencies: []
  config:
    name: mixtral
    resources:
      gpu: 2
      gpu_type: nvidia-a100-80g
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: mixtral
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
