alias:
- 124b-2411
- 124b
engine_config:
  dtype: half
  enable_chunked_prefill: false
  enable_prefix_caching: false
  limit_mm_per_prompt:
    image: 5
  max_model_len: 16384
  model: mistralai/Pixtral-Large-Instruct-2411
  tensor_parallel_size: 4
  tokenizer_mode: mistral
project: vllm-chat
requirements:
- mistral_common[opencv]
service_config:
  envs:
  - name: HF_TOKEN
  name: pixtral
  resources:
    gpu: 4
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
vision: true
