engine_config:
  dtype: half
  max_model_len: 2048
  model: google/gemma-2-9b-it
extra_envs:
- name: VLLM_ATTENTION_BACKEND
  value: FLASHINFER
- name: HF_TOKEN
extra_labels:
  model_name: google/gemma-2-9b-it
  openllm_alias: 9b,9b-instruct
project: vllm-chat
service_config:
  name: gemma2
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
