engine_config:
  max_model_len: 4096
  model: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
  openllm_alias: 14b,14b-instruct
project: vllm-chat
server_config:
  enable_reasoning: true
  reasoning_parser: deepseek_r1
service_config:
  name: deepseek-r1-distill
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
