engine_config:
  max_model_len: 20480
  model: Qwen/Qwen2.5-Coder-7B-Instruct
extra_labels:
  model_name: Qwen/Qwen2.5-Coder-7B-Instruct
  openllm_alias: 7b
project: vllm-chat
service_config:
  name: qwen2.5-coder
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
