engine_config:
  additional_files:
  - qwen2.5-14b-instruct-q8_0-00001-of-00004.gguf
  - qwen2.5-14b-instruct-q8_0-00002-of-00004.gguf
  - qwen2.5-14b-instruct-q8_0-00003-of-00004.gguf
  - qwen2.5-14b-instruct-q8_0-00004-of-00004.gguf
  filename: qwen2.5-14b-instruct-q8_0-00001-of-00004.gguf
  max_model_len: 2048
  repo_id: Qwen/Qwen2.5-14B-Instruct-GGUF
labels:
  platforms: darwin
project: llamacpp-chat
service_config:
  envs:
  - name: CMAKE_ARGS
    value: -DGGML_METAL=on
  name: qwen2.5
  resources:
    memory: 60Gi
  traffic:
    timeout: 300
