alias:
- 123b-2407
- 123b
build:
  exclude:
  - consolidated*
engine_config:
  dtype: half
  max_model_len: 2048
  model: mistralai/Mistral-Large-Instruct-2407
  tensor_parallel_size: 4
project: vllm-chat
service_config:
  envs:
  - name: HF_TOKEN
  name: mistral-large
  resources:
    gpu: 4
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
