service: service:VLLM
name: mistral-large
version: 123b-instruct-awq-4bit-a39f
bentoml_version: 1.3.14
creation_time: '2024-11-21T09:05:15.671213+00:00'
labels:
  model_name: casperhansen/mistral-large-instruct-2407-awq
  openllm_alias: 123b-4bit,123b-instruct-2407-4bit
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: mistral-large
services:
- name: mistral-large
  service: ''
  models:
  - tag: casperhansen--mistral-large-instruct-2407-awq:1b91a828d8121dc12dbd493ebfc9cdf4b0a861c3
    module: null
    creation_time: '2024-11-21T09:05:15.669301+00:00'
    registry: huggingface
    metadata:
      model_id: casperhansen/mistral-large-instruct-2407-awq
      revision: 1b91a828d8121dc12dbd493ebfc9cdf4b0a861c3
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: mistral-large
    resources:
      gpu: 1
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs: []
schema:
  name: mistral-large
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
