service: service:VLLM
name: gemma
version: 7b-instruct-awq-4bit-b214
bentoml_version: 1.3.7
creation_time: '2024-09-27T09:48:11.473412+00:00'
labels:
  model_name: casperhansen/gemma-7b-it-awq
  openllm_alias: 7b-4bit,7b-instruct-4bit
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
runners: []
entry_service: gemma
services:
- name: gemma
  service: ''
  models: []
  dependencies: []
  config:
    name: gemma
    resources:
      gpu: 1
      gpu_type: nvidia-rtx-3060
    traffic:
      timeout: 300
envs: []
schema:
  name: gemma
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
