engine_config:
  max_model_len: 2048
  model: meta-llama/Llama-3.3-70B-Instruct
  tensor_parallel_size: 2
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: meta-llama/Llama-3.3-70B-Instruct
  openllm_alias: 70b,70b-instruct
project: vllm-chat
service_config:
  name: llama3.3
  resources:
    gpu: 2
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
