service: service:VLLM
name: llama2
version: 13b-chat-fp16-49e4
bentoml_version: 1.3.20
creation_time: '2025-01-22T07:12:59.236439+00:00'
labels:
  model_name: meta-llama/Llama-2-13b-chat-hf
  openllm_alias: 13b,13b-chat
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: llama2
services:
- name: llama2
  service: ''
  models:
  - tag: meta-llama--llama-2-13b-chat-hf:44a6d46ca4422dbb4e6a43ab64301faf
    module: null
    creation_time: '2025-01-22T07:12:59.234622+00:00'
    registry: huggingface
    metadata:
      model_id: meta-llama/llama-2-13b-chat-hf
      revision: a2cb7a712bb6e5e736ca7f8cd98167f81a0b5bd8
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: llama2
    resources:
      gpu: 1
      gpu_type: nvidia-tesla-a100
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: llama2
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
