service: service:VLLM
name: deepseek-r1-distill
version: llama3.3-70b-instruct-fp16-03c5
bentoml_version: 1.3.20
creation_time: '2025-01-30T17:45:17.214343+00:00'
labels:
  model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-70B
  openllm_alias: 70b,70b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: deepseek-r1-distill
services:
- name: deepseek-r1-distill
  service: ''
  models:
  - tag: deepseek-ai--deepseek-r1-distill-llama-70b:d17bbdba22b1bbff2a31ec773f2a2d52
    module: null
    creation_time: '2025-01-30T17:45:17.212599+00:00'
    registry: huggingface
    metadata:
      model_id: deepseek-ai/deepseek-r1-distill-llama-70b
      revision: 1772b078b94935926dcc8715c1afdd04ae447080
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: deepseek-r1-distill
    resources:
      gpu: 2
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs: []
schema:
  name: deepseek-r1-distill
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
