engine_config:
  model: deepseek-ai/DeepSeek-R1
  tensor_parallel_size: 16
  trust_remote_code: true
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: deepseek-ai/DeepSeek-R1
  openllm_alias: 671b,671b-bfloat16,r1
project: vllm-chat
server_config:
  enable_reasoning: true
  reasoning_parser: deepseek_r1
service_config:
  name: deepseek-v3
  resources:
    gpu: 16
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
