alias:
- 70b
build:
  exclude:
  - original
  - consolidated*
engine_config:
  max_model_len: 4096
  model: meta-llama/Llama-3.3-70B-Instruct
  tensor_parallel_size: 2
project: vllm-chat
server_config:
  tool_call_parser: pythonic
service_config:
  envs:
  - name: HF_TOKEN
  name: llama3.3
  resources:
    gpu: 2
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
