service: service:VLLM
name: llama2
version: 7b-chat-awq-4bit-0c30
bentoml_version: 1.3.14
creation_time: '2024-11-21T09:04:38.405152+00:00'
labels:
  model_name: TheBloke/Llama-2-7B-Chat-AWQ
  openllm_alias: 7b-4bit,7b-chat-4bit
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: llama2
services:
- name: llama2
  service: ''
  models:
  - tag: thebloke--llama-2-7b-chat-awq:ee91097dc818c742d9b648147891dfadd9638ace
    module: null
    creation_time: '2024-11-21T09:04:38.403267+00:00'
    registry: huggingface
    metadata:
      model_id: thebloke/llama-2-7b-chat-awq
      revision: ee91097dc818c742d9b648147891dfadd9638ace
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: llama2
    resources:
      gpu: 1
      gpu_type: nvidia-rtx-3060
    traffic:
      timeout: 300
envs: []
schema:
  name: llama2
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
