engine_config:
  max_model_len: 2048
  model: deepseek-ai/DeepSeek-V3
  tensor_parallel_size: 16
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: deepseek-ai/DeepSeek-V3
  openllm_alias: 671b,671b-bfloat16
project: vllm-chat
service_config:
  name: deepseek-v3
  resources:
    gpu: 16
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
