service: service:VLLM
name: llama4
version: 17b-128e-maverick-instruct-daf5
bentoml_version: 1.4.7
creation_time: '2025-04-08T02:03:54.728578+00:00'
labels:
  generator: openllm
  owner: bentoml-team
  aliases: 17b128e,maverick
models: []
entry_service: llama4
services:
- name: llama4
  service: ''
  models:
  - tag: meta-llama--llama-4-maverick-17b-128e-instruct:f3abde803697f5d649453ee9a8f7d524
    module: null
    creation_time: '2025-04-08T02:03:54.683189+00:00'
    registry: huggingface
    metadata:
      model_id: meta-llama/llama-4-maverick-17b-128e-instruct
      revision: c33770d34695b047805ab5b952a20d4d76b5b3dc
      endpoint: https://huggingface.co
      include: null
      exclude:
      - original
      - consolidated*
      - '*.pth'
      - '*.pt'
  dependencies: []
  config:
    name: llama4
    resources:
      gpu: 8
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
- name: VLLM_USE_V1
  value: '0'
- name: UV_NO_PROGRESS
  value: '1'
- name: HF_HUB_DISABLE_PROGRESS_BARS
  value: '1'
- name: VLLM_LOGGING_CONFIG_PATH
  value: /tmp/tmpluksa44p/logging-config.json
schema:
  name: llama4
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: Who are you? Please respond in pirate speak!
          title: Prompt
          type: string
        max_tokens:
          default: 2048
          maximum: 2048
          minimum: 128
          title: Max Tokens
          type: integer
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: sights
    route: /sights
    batchable: false
    input:
      properties:
        prompt:
          default: Who are you? Please respond in pirate speak!
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
        max_tokens:
          default: 2048
          maximum: 2048
          minimum: 128
          title: Max Tokens
          type: integer
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 2
image:
  base_image: python:3.11-slim
  python_version: '3.11'
  commands:
  - apt-get update && apt-get install -q -y --no-install-recommends --allow-remove-essential
    ca-certificates gnupg2 bash build-essential git
  python_requirements: 'bentoml==1.4.7

    vllm==0.8.3

    kantoku>=0.18.1

    fastapi

    openai>=1.67.0

    pyyaml

    Pillow

    bentoml==1.4.7

    '
  post_commands:
  - uv pip install --compile-bytecode flashinfer-python --find-links https://flashinfer.ai/whl/cu124/torch2.5
