service: service:VLLM
name: qwen2
version: 72b-instruct-awq-4bit-0e35
bentoml_version: 1.3.20
creation_time: '2025-01-30T17:44:51.340170+00:00'
labels:
  model_name: Qwen/Qwen2-72B-Instruct-AWQ
  openllm_alias: 72b-4bit,72b-instruct-4bit
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: qwen2
services:
- name: qwen2
  service: ''
  models:
  - tag: qwen--qwen2-72b-instruct-awq:3be35cf53cd7a125d25495fc819d6dfb
    module: null
    creation_time: '2025-01-30T17:44:51.338379+00:00'
    registry: huggingface
    metadata:
      model_id: qwen/qwen2-72b-instruct-awq
      revision: 26975fbe12cda45e38c0b99da62f1a7deab1bf25
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: qwen2
    resources:
      gpu: 1
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs: []
schema:
  name: qwen2
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
