engine_config:
  dtype: half
  max_model_len: 2048
  model: meta-llama/Meta-Llama-3.2-1B-Instruct
extra_labels:
  model_name: meta-llama/Meta-Llama-3.2-1B-Instruct
  openllm_alias: 1b,1b-instruct
project: vllm-chat
service_config:
  name: llama3.2
  resources:
    gpu: 1
    gpu_type: nvidia-rtx-3060
  traffic:
    timeout: 300
