alias:
- 8b
embedding: true
engine_config:
  max_model_len: 3192
  model: meta-llama/Meta-Llama-3.1-8B-Instruct
project: vllm-chat
server_config:
  tool_call_parser: llama3_json
service_config:
  envs:
  - name: HF_TOKEN
  name: llama3.1
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
