alias:
- 32b-w8a8
engine_config:
  max_model_len: 8192
  model: Qwen/Qwen2.5-32B-Instruct-GPTQ-Int8
project: vllm-chat
server_config:
  tool_call_parser: llama3_json
service_config:
  name: qwen2.5
  resources:
    gpu: 1
    gpu_type: nvidia-tesla-a100
  traffic:
    timeout: 300
