engine_config:
  dtype: half
  model: mistralai/Ministral-8B-Instruct-2410
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: mistralai/Ministral-8B-Instruct-2410
  openllm_alias: 7b,7b-instruct
project: vllm-chat
service_config:
  name: mistral
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
