service: service:VLLM
name: qwen2
version: 57b-a14b-instruct-fp16-072b
bentoml_version: 1.3.19
creation_time: '2025-01-08T02:26:04.757103+00:00'
labels:
  model_name: Qwen/Qwen2-57B-A14B-Instruct
  openllm_alias: 57b-a14b,57b-a14b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: qwen2
services:
- name: qwen2
  service: ''
  models:
  - tag: qwen--qwen2-57b-a14b-instruct:8aee6d31291df1a764d658c399ca713f
    module: null
    creation_time: '2025-01-08T02:26:04.754896+00:00'
    registry: huggingface
    metadata:
      model_id: qwen/qwen2-57b-a14b-instruct
      revision: 50896d66b39f1425d63720541a66c7df13e053c0
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: qwen2
    resources:
      gpu: 2
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs: []
schema:
  name: qwen2
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
