alias:
- 17b128e
- maverick
build:
  exclude:
  - original
  - consolidated*
engine_config:
  max_model_len: 4096
  model: meta-llama/Llama-4-Maverick-17B-128E-Instruct
  tensor_parallel_size: 8
project: vllm-chat
server_config:
  max_model_len: 430000
  override_generation_config:
    attn_temperature_tuning: true
  tensor_parallel_size: 8
  tool_call_parser: pythonic
service_config:
  envs:
  - name: HF_TOKEN
  - name: VLLM_DISABLE_COMPILE_CACHE
    value: 1
  name: llama4
  resources:
    gpu: 8
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
vision: true
