service: service:VLLM
name: qwen2.5-coder
version: 7b-instruct-e027
bentoml_version: 1.3.12
creation_time: '2024-11-18T08:58:23.678363+00:00'
labels:
  model_name: Qwen/Qwen2.5-Coder-7B-Instruct
  openllm_alias: 7b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: qwen2.5-coder
services:
- name: qwen2.5-coder
  service: ''
  models:
  - tag: qwen--qwen2.5-coder-7b-instruct:4bbe56d41897ba0fff8b3c9cd18cc56b8a23bbc8
    module: null
    creation_time: '2024-11-18T08:58:23.676678+00:00'
    registry: huggingface
    metadata:
      model_id: qwen/qwen2.5-coder-7b-instruct
      revision: 4bbe56d41897ba0fff8b3c9cd18cc56b8a23bbc8
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: qwen2.5-coder
    resources:
      gpu: 1
      gpu_type: nvidia-l4
    traffic:
      timeout: 300
envs: []
schema:
  name: qwen2.5-coder
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
