engine_config:
  model: mistralai/Mistral-Small-24B-Instruct-2501
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: mistralai/Mistral-Small-24B-Instruct-2501
  openllm_alias: 24b, 24b-instruct-2501
project: vllm-chat
service_config:
  name: mistral
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
