service: service:VLLM
name: mistral
version: 7b-instruct-fp16-26bd
bentoml_version: 1.3.20
creation_time: '2025-01-22T07:13:07.552521+00:00'
labels:
  model_name: mistralai/Mistral-7B-Instruct-v0.1
  openllm_alias: 7b,7b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: mistral
services:
- name: mistral
  service: ''
  models:
  - tag: mistralai--mistral-7b-instruct-v0.1:fa2dfaf758bda7943191581b9ef0c971
    module: null
    creation_time: '2025-01-22T07:13:07.550716+00:00'
    registry: huggingface
    metadata:
      model_id: mistralai/mistral-7b-instruct-v0.1
      revision: 2dcff66eac0c01dc50e4c41eea959968232187fe
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: mistral
    resources:
      gpu: 1
      gpu_type: nvidia-l4
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: mistral
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
