alias:
- 32b
engine_config:
  max_model_len: 8192
  model: Qwen/QwQ-32B
project: vllm-chat
server_config:
  enable_auto_tool_choice: true
  enable_reasoning: true
  reasoning_parser: deepseek_r1
  tool_call_parser: llama3_json
service_config:
  envs:
  - name: HF_TOKEN
  - name: UV_NO_BUILD_ISOLATION
    value: 1
  name: qwq
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
