service: service:VLLM
name: gemma2
version: 9b-instruct-fp16-6110
bentoml_version: 1.3.10
creation_time: '2024-10-31T01:33:08.926903+00:00'
labels:
  model_name: google/gemma-2-9b-it
  openllm_alias: 9b,9b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: gemma2
services:
- name: gemma2
  service: ''
  models: []
  dependencies: []
  config:
    name: gemma2
    resources:
      gpu: 1
      gpu_type: nvidia-tesla-l4
    traffic:
      timeout: 300
envs:
- name: VLLM_ATTENTION_BACKEND
  value: FLASHINFER
- name: HF_TOKEN
  value: ''
schema:
  name: gemma2
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    VLLM_ATTENTION_BACKEND: FLASHINFER
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
