engine_config:
  max_model_len: 4096
  model: deepseek-ai/DeepSeek-R1
  tensor_parallel_size: 16
  trust_remote_code: true
extra_envs:
- name: HF_TOKEN
project: vllm-chat
server_config:
  enable_reasoning: true
  reasoning_parser: deepseek_r1
service_config:
  name: deepseek-v3
  resources:
    gpu: 16
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
