service: service:VLLM
name: mistral-large
version: 123b-instruct-fp16-c0fa
bentoml_version: 1.3.14
creation_time: '2024-11-21T09:05:09.430971+00:00'
labels:
  model_name: mistralai/Mistral-Large-Instruct-2407
  openllm_alias: 123b, 123b-instruct-2407
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: mistral-large
services:
- name: mistral-large
  service: ''
  models:
  - tag: mistralai--mistral-large-instruct-2407:c6a230e7b1070914dd28bd6bc3b9c7c3d9e612ae
    module: null
    creation_time: '2024-11-21T09:05:09.428939+00:00'
    registry: huggingface
    metadata:
      model_id: mistralai/mistral-large-instruct-2407
      revision: c6a230e7b1070914dd28bd6bc3b9c7c3d9e612ae
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: mistral-large
    resources:
      gpu: 4
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: mistral-large
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
