service: service:VLLM
name: llama3.2
version: 1b-instruct-fp16-69ad
bentoml_version: 1.3.14
creation_time: '2024-11-21T09:05:46.496030+00:00'
labels:
  model_name: meta-llama/Llama-3.2-1B-Instruct
  openllm_alias: 1b,1b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: llama3.2
services:
- name: llama3.2
  service: ''
  models:
  - tag: meta-llama--llama-3.2-1b-instruct:9213176726f574b556790deb65791e0c5aa438b6
    module: null
    creation_time: '2024-11-21T09:05:46.494053+00:00'
    registry: huggingface
    metadata:
      model_id: meta-llama/llama-3.2-1b-instruct
      revision: 9213176726f574b556790deb65791e0c5aa438b6
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: llama3.2
    resources:
      gpu: 1
      gpu_type: nvidia-rtx-3060
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: llama3.2
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
