alias:
- r1-qwen2.5-14b-w4a16
engine_config:
  max_model_len: 4096
  model: neuralmagic/DeepSeek-R1-Distill-Qwen-14B-quantized.w4a16
project: vllm-chat
server_config:
  reasoning_parser: deepseek_r1
  tool_call_parser: llama3_json
service_config:
  name: bentovllm-r1-qwen2.5-14b-w4a16-service
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
