alias:
- 27b
engine_config:
  max_model_len: 16384
  model: google/gemma-3-27b-it
project: vllm-chat
service_config:
  envs:
  - name: HF_TOKEN
  name: gemma3
  resources:
    gpu: 1
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
