engine_config:
  model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
  openllm_alias: 7b,7b-math
project: vllm-chat
server_config:
  enable_reasoning: true
  reasoning_parser: deepseek_r1
service_config:
  name: deepseek-r1-distill
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
