alias:
- 90b
build:
  exclude:
  - original
engine_config:
  enforce_eager: true
  limit_mm_per_prompt:
    image: 1
  max_model_len: 16384
  max_num_seqs: 16
  model: meta-llama/Llama-3.2-90B-Vision-Instruct
project: vllm-chat
server_config:
  tool_call_parser: pythonic
service_config:
  envs:
  - name: HF_TOKEN
  name: llama3.2
  resources:
    gpu: 2
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
vision: true
