engine_config:
  dtype: half
  max_model_len: 2048
  model: google/gemma-2b-it
extra_envs:
- name: HF_TOKEN
extra_labels:
  model_name: google/gemma-2b-it
  openllm_alias: 2b,2b-instruct
project: vllm-chat
service_config:
  name: gemma
  resources:
    gpu: 1
    gpu_type: nvidia-rtx-3060
  traffic:
    timeout: 300
