service: service:VLLM
name: qwen2.5-coder
version: 32b-instruct-2ca2
bentoml_version: 1.3.20
creation_time: '2025-01-22T07:15:24.967103+00:00'
labels:
  model_name: Qwen/Qwen2.5-Coder-32B-Instruct
  openllm_alias: 32b
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: qwen2.5-coder
services:
- name: qwen2.5-coder
  service: ''
  models:
  - tag: qwen--qwen2.5-coder-32b-instruct:c0a16df3f5c059e38344467ab124f66e
    module: null
    creation_time: '2025-01-22T07:15:24.965203+00:00'
    registry: huggingface
    metadata:
      model_id: qwen/qwen2.5-coder-32b-instruct
      revision: 381fc969f78efac66bc87ff7ddeadb7e73c218a7
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: qwen2.5-coder
    resources:
      gpu: 1
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs: []
schema:
  name: qwen2.5-coder
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
