service: service:VLLM
name: jamba1.5
version: mini-fp16-dddc
bentoml_version: 1.3.14
creation_time: '2024-11-21T09:09:33.120294+00:00'
labels:
  model_name: ai21labs/AI21-Jamba-1.5-Mini
  openllm_alias: mini
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: jamba1.5
services:
- name: jamba1.5
  service: ''
  models:
  - tag: ai21labs--ai21-jamba-1.5-mini:1840d3373c51e4937f4dbaaaaf8cac1427b46858
    module: null
    creation_time: '2024-11-21T09:09:33.118425+00:00'
    registry: huggingface
    metadata:
      model_id: ai21labs/ai21-jamba-1.5-mini
      revision: 1840d3373c51e4937f4dbaaaaf8cac1427b46858
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: jamba1.5
    resources:
      gpu: 4
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: jamba1.5
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
