engine_config:
  dtype: half
  max_model_len: 2048
  model: deepseek-ai/DeepSeek-R1-Distill-Llama-70B
  tensor_parallel_size: 2
extra_labels:
  model_name: deepseek-ai/DeepSeek-R1-Distill-Llama-70B
  openllm_alias: 70b,70b-instruct
project: vllm-chat
service_config:
  name: deepseek-r1-distill
  resources:
    gpu: 2
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
