alias:
- 3b
embedding: true
engine_config:
  max_model_len: 8192
  model: meta-llama/Llama-3.2-3B-Instruct
project: vllm-chat
server_config:
  tool_call_parser: pythonic
service_config:
  envs:
  - name: HF_TOKEN
  name: llama3.2
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
v1: true
