service: service:VLLM
name: llama3.3
version: 70b-instruct-fp16-a20b
bentoml_version: 1.3.19
creation_time: '2025-01-06T13:11:11.623486+00:00'
labels:
  model_name: meta-llama/Llama-3.3-70B-Instruct
  openllm_alias: 70b,70b-instruct
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: llama3.3
services:
- name: llama3.3
  service: ''
  models:
  - tag: meta-llama--llama-3.3-70b-instruct:72024badd10f4b5526da4f5eebabefd7
    module: null
    creation_time: '2025-01-06T13:11:11.621944+00:00'
    registry: huggingface
    metadata:
      model_id: meta-llama/llama-3.3-70b-instruct
      revision: 6f6073b423013f6a7d4d9f39144961bfbfbc386b
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: llama3.3
    resources:
      gpu: 2
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: llama3.3
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
