alias:
- 17b16e
- scout
build:
  exclude:
  - original
  - consolidated*
engine_config:
  max_model_len: 4096
  model: meta-llama/Llama-4-Scout-17B-16E-Instruct
  tensor_parallel_size: 2
project: vllm-chat
server_config:
  max_num_seqs: 16
  tool_call_parser: pythonic
service_config:
  envs:
  - name: HF_TOKEN
  name: llama4
  resources:
    gpu: 2
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
vision: true
