service: service:VLLM
name: llama3.1
version: 405b-instruct-awq-4bit-3f82
bentoml_version: 1.3.14
creation_time: '2024-11-21T09:06:29.509564+00:00'
labels:
  model_name: hugging-quants/Meta-Llama-3.1-405B-Instruct-AWQ-INT4
  openllm_alias: 405b-4bit,405b-instruct-4bit
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: llama3.1
services:
- name: llama3.1
  service: ''
  models:
  - tag: hugging-quants--meta-llama-3.1-405b-instruct-awq-int4:1954fc5977cde8271bd7fd3e9bbb827a7bdd3bcd
    module: null
    creation_time: '2024-11-21T09:06:29.507590+00:00'
    registry: huggingface
    metadata:
      model_id: hugging-quants/meta-llama-3.1-405b-instruct-awq-int4
      revision: 1954fc5977cde8271bd7fd3e9bbb827a7bdd3bcd
      endpoint: https://huggingface.co
  dependencies: []
  config:
    name: llama3.1
    resources:
      gpu: 4
      gpu_type: nvidia-a100-80gb
    traffic:
      timeout: 300
envs: []
schema:
  name: llama3.1
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      title: IORootModel[str]
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
