engine_config:
  max_model_len: 2048
  model: Qwen/Qwen2.5-VL-7B-Instruct
extra_requirements:
- qwen-vl-utils[decord]==0.0.8
project: vllm-chat
service_config:
  name: qwen2.5vl
  resources:
    gpu: 1
    gpu_type: nvidia-l4
  traffic:
    timeout: 300
vision: true
