engine_config:
  max_model_len: 2048
  model: mistralai/Mixtral-8x7B-Instruct-v0.1
  tensor_parallel_size: 2
extra_envs:
- name: HF_TOKEN
project: vllm-chat
service_config:
  name: mixtral
  resources:
    gpu: 2
    gpu_type: nvidia-a100-80gb
  traffic:
    timeout: 300
